image: moodlehq/moodle-php-apache:8.1   # Defines PHP version image to use.

services:
  - name: selenium/standalone-chrome:3
    alias: behat
  - name: mysql:8.0
    alias: db
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--innodb_file_per_table=On'
      - '--wait-timeout=28800'
      - '--skip-log-bin'

cache:
  paths:
    - .cache

variables:
  DEBIAN_FRONTEND: 'noninteractive'
  COMPOSER_ALLOW_SUPERUSER: 1
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.cache/npm"
  CI_BUILD_DIR: '/tmp/plugin'
  MOODLE_BRANCH: 'MOODLE_405_STABLE'      # Defines Moodle branch.
  MOODLE_BEHAT_WWWROOT: 'http://localhost:8000'
  MOODLE_BEHAT_WDHOST: 'http://behat:4444/wd/hub'
  MOODLE_START_BEHAT_SERVERS: 'no'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  DB: 'mysqli'

stages:
  - moodle-plugin-ci

.setup: &setup
  before_script:
    - mkdir -pv "$CI_BUILD_DIR"
    - cp -ru "$CI_PROJECT_DIR/"* "$CI_BUILD_DIR"
    - mkdir -p /usr/share/man/man1 /usr/share/man/man3 /usr/share/man/man7
    - apt-get -qq update
    - apt-get -yqq install --no-install-suggests default-jre-headless default-mysql-client
    - 'curl -sS https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh | bash'
    - . ~/.bashrc
    - nvm install --default --latest-npm lts/gallium
    - 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
    - composer create-project -n --no-dev --no-progress --no-ansi moodlehq/moodle-plugin-ci /opt/mci ^4
    - export PATH="/opt/mci/bin:/opt/mci/vendor/bin:$PATH"
    - git config --global http.sslVerify false      # Only required if the plugin has dependency.
    - moodle-plugin-ci install --db-host db --db-name moodle
    - '{ php -S 0.0.0.0:8000 -t "$CI_PROJECT_DIR/moodle" >/dev/null 2>&1 & }'
  script:
    echo "Setup complete"

phplint:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci phplint

phpmd:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci phpmd

codechecker:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci codechecker --max-warnings 0

phpdoc:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci phpdoc --max-warnings 0

validate:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci validate

savepoints:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci savepoints

mustache:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci mustache

grunt:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci grunt --max-lint-warnings 0

phpunit:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci phpunit

behat:
  tags:
    - docker
  <<: *setup
  stage: moodle-plugin-ci
  script:
    - moodle-plugin-ci behat --auto-rerun 0 --profile chrome
